spring:
  datasource:
    name: bcpf
    url: jdbc:mysql://127.0.0.1:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: sso
    password: sso
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 200
    initialSize: 20
    maxWait: 10000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #邮箱配置
  mail:
    host: smtp.qq.com
    port: 25
    username: 1056196129@qq.com
    password: afimeijvkfplbcdd
    nick: 测试
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#日志文件输出目录和文件
logging:
  path: d://temp//logs
  file: demo